---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoind
  labels:
    app: bitcoind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
      - name: bitcoind
        image: metrictwo/bitcoind:v1
        ports:
        - containerPort: 8333
        volumeMounts:
        # Our image uses a data-dir of /bitcoin. Give how much space can be
        # needed, this should be externally mounted
        - mountPath: /bitcoin
          name: data-dir
      volumes:
      - name: bitcoin-data-dir
        # This example uses a simple hostPath. IRL, you'd use whatever your
        # volume provider is (e.g. Ceph, EBS, etc)
        hostPath:
          path: /var/lib/bitcoin
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: bitcoind
spec:
  selector:
    app: bitcoind
  ports:
  - protocol: TCP
    port: 8333
    targetPort: 8333
  type: LoadBalancer
